# Header

menu:
  主页: /
  随笔: /tags/随笔/
  读书: /books     #This is your books page
  电影: /movies   #This is your movies page

# SubNav
subnav:
  github: "https://github.com/xingguanxiaohai"
  weibo: "http://weibo.com/122101047"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/qian-xiao-wu-hen"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:632068499@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
# 已经将项目的page服务 改为用户Pages
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢您请我吃番茄'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.png
# 微信二维码图片地址
weixin: /assets/img/wechat.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/head.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '好基友'
  aboutme: '关于我'

friends:
  Myths: https://blog.mythsman.com/
  一旦: http://blog.csdn.net/u013887254
  小学生反弹: https://titanssword.github.io/
  时而宁靜: http://blog.csdn.net/ty_hf
  番茄: http://blog.csdn.net/i_am_tomato
  汪小智: http://blog.csdn.net/wlzjiayou
  剑神: http://blog.csdn.net/u012315428/

aboutme: 爱生活，爱妹纸，更爱编程。<br><br><br>&nbsp;&nbsp;&nbsp;&nbsp;胆小认生，不易相处，<br>      年轻无为，卖码为生。<br>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   --- Tomato.Yan